sudo: false
language: python
python:
- '2.7'
install:
- pip install pygments lxml setuptools --upgrade
- git clone https://github.com/tabatkins/bikeshed.git
- pip install --editable $PWD/bikeshed
- bikeshed update
script:
- bash "./deploy.sh"

env:
  global:
  - ENCRYPTION_LABEL="4571b087bd76"
  - COMMIT_AUTHOR_EMAIL="plh+deploy@w3.org"
  - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"

after_success:
  - echo "If it fails, check https://lists.w3.org/Archives/Public/public-tr-notifications/"
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bikeshed echidna --md-status=WD --u "$USER" --p "$PASS" --decision "$DECISION" --cc="marcos@marcosc.com"'
